name = "Omniscape"
uuid = "a38d70fc-99f5-11e9-1e3d-cbca093024c3"
authors = ["Vincent A. Landau <vincent@csp-inc.org>"]
version = "0.0.3"

[deps]
Circuitscape = "2b7a1792-8151-5239-925d-e2b8fdfa3201"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[compat]
Circuitscape = "≥ 5.5.3"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
